# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout-main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(739, 446)
        main_window.setStyleSheet("background-color: rgb(18, 18, 18);")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.stacked_windows = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_windows.setGeometry(QtCore.QRect(0, -20, 731, 441))
        self.stacked_windows.setObjectName("stacked_windows")
        self.page_main_menu = QtWidgets.QWidget()
        self.page_main_menu.setObjectName("page_main_menu")
        self.app_descr = QtWidgets.QTextBrowser(self.page_main_menu)
        self.app_descr.setGeometry(QtCore.QRect(100, 130, 551, 81))
        self.app_descr.setStyleSheet("font: 20pt \"Sans Serif\";\n"
"")
        self.app_descr.setObjectName("app_descr")
        self.button_15min_words = QtWidgets.QPushButton(self.page_main_menu)
        self.button_15min_words.setGeometry(QtCore.QRect(430, 240, 201, 23))
        self.button_15min_words.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_15min_words.setObjectName("button_15min_words")
        self.button_exit = QtWidgets.QPushButton(self.page_main_menu)
        self.button_exit.setGeometry(QtCore.QRect(340, 400, 80, 23))
        self.button_exit.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_exit.setObjectName("button_exit")
        self.speed_cards_button = QtWidgets.QPushButton(self.page_main_menu)
        self.speed_cards_button.setGeometry(QtCore.QRect(140, 240, 91, 23))
        self.speed_cards_button.setStyleSheet("color: rgb(255, 255, 255);")
        self.speed_cards_button.setObjectName("speed_cards_button")
        self.app_title = QtWidgets.QLabel(self.page_main_menu)
        self.app_title.setGeometry(QtCore.QRect(210, 60, 331, 71))
        self.app_title.setStyleSheet("font: 30pt \"Sans Serif\";\n"
"color: rgb(255, 56, 56)")
        self.app_title.setObjectName("app_title")
        self.button_5min_num = QtWidgets.QPushButton(self.page_main_menu)
        self.button_5min_num.setGeometry(QtCore.QRect(260, 240, 141, 23))
        self.button_5min_num.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_5min_num.setObjectName("button_5min_num")
        self.button_sn = QtWidgets.QPushButton(self.page_main_menu)
        self.button_sn.setGeometry(QtCore.QRect(140, 290, 121, 23))
        self.button_sn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_sn.setObjectName("button_sn")
        self.button_bn = QtWidgets.QPushButton(self.page_main_menu)
        self.button_bn.setGeometry(QtCore.QRect(280, 290, 121, 23))
        self.button_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_bn.setObjectName("button_bn")
        self.heart_img = QtWidgets.QLabel(self.page_main_menu)
        self.heart_img.setGeometry(QtCore.QRect(560, 70, 41, 41))
        self.heart_img.setText("")
        self.heart_img.setPixmap(QtGui.QPixmap("love.png"))
        self.heart_img.setScaledContents(True)
        self.heart_img.setObjectName("heart_img")
        self.stacked_windows.addWidget(self.page_main_menu)
        self.page_speedcards = QtWidgets.QWidget()
        self.page_speedcards.setObjectName("page_speedcards")
        self.time_delay_label = QtWidgets.QLabel(self.page_speedcards)
        self.time_delay_label.setGeometry(QtCore.QRect(30, 60, 121, 16))
        self.time_delay_label.setStyleSheet("color:rgb(255, 255, 255)")
        self.time_delay_label.setObjectName("time_delay_label")
        self.button_begin = QtWidgets.QPushButton(self.page_speedcards)
        self.button_begin.setGeometry(QtCore.QRect(30, 100, 80, 23))
        self.button_begin.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_begin.setObjectName("button_begin")
        self.button_pause = QtWidgets.QPushButton(self.page_speedcards)
        self.button_pause.setGeometry(QtCore.QRect(130, 100, 80, 23))
        self.button_pause.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_pause.setObjectName("button_pause")
        self.button_hide_timer = QtWidgets.QPushButton(self.page_speedcards)
        self.button_hide_timer.setGeometry(QtCore.QRect(230, 100, 80, 23))
        self.button_hide_timer.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_hide_timer.setObjectName("button_hide_timer")
        self.button_recall = QtWidgets.QPushButton(self.page_speedcards)
        self.button_recall.setGeometry(QtCore.QRect(330, 100, 80, 23))
        self.button_recall.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_recall.setObjectName("button_recall")
        self.spinBox = QtWidgets.QSpinBox(self.page_speedcards)
        self.spinBox.setGeometry(QtCore.QRect(160, 60, 61, 24))
        self.spinBox.setStyleSheet("background-color: rgb(102, 102, 102);")
        self.spinBox.setObjectName("spinBox")
        self.button_quit = QtWidgets.QPushButton(self.page_speedcards)
        self.button_quit.setGeometry(QtCore.QRect(430, 100, 141, 23))
        self.button_quit.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_quit.setObjectName("button_quit")
        self.button_exit_2 = QtWidgets.QPushButton(self.page_speedcards)
        self.button_exit_2.setGeometry(QtCore.QRect(590, 100, 80, 23))
        self.button_exit_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_exit_2.setObjectName("button_exit_2")
        self.card_image = QtWidgets.QLabel(self.page_speedcards)
        self.card_image.setGeometry(QtCore.QRect(270, 150, 181, 261))
        self.card_image.setText("")
        self.card_image.setPixmap(QtGui.QPixmap("card_images/7S.png"))
        self.card_image.setObjectName("card_image")
        self.lcdNumber = QtWidgets.QLCDNumber(self.page_speedcards)
        self.lcdNumber.setGeometry(QtCore.QRect(590, 160, 111, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.seconds_label = QtWidgets.QLabel(self.page_speedcards)
        self.seconds_label.setGeometry(QtCore.QRect(230, 60, 51, 21))
        self.seconds_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.seconds_label.setObjectName("seconds_label")
        self.checkBox = QtWidgets.QCheckBox(self.page_speedcards)
        self.checkBox.setGeometry(QtCore.QRect(590, 210, 85, 21))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.button_next_sc = QtWidgets.QPushButton(self.page_speedcards)
        self.button_next_sc.setGeometry(QtCore.QRect(590, 280, 80, 23))
        self.button_next_sc.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_next_sc.setObjectName("button_next_sc")
        self.button_prev_sc = QtWidgets.QPushButton(self.page_speedcards)
        self.button_prev_sc.setGeometry(QtCore.QRect(590, 320, 80, 23))
        self.button_prev_sc.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_prev_sc.setObjectName("button_prev_sc")
        self.card_no_sc = QtWidgets.QLabel(self.page_speedcards)
        self.card_no_sc.setGeometry(QtCore.QRect(530, 300, 41, 20))
        self.card_no_sc.setStyleSheet("color:rgb(255, 255, 255)")
        self.card_no_sc.setObjectName("card_no_sc")
        self.stacked_windows.addWidget(self.page_speedcards)
        self.page_5min_nums = QtWidgets.QWidget()
        self.page_5min_nums.setObjectName("page_5min_nums")
        self.button_quit_2 = QtWidgets.QPushButton(self.page_5min_nums)
        self.button_quit_2.setGeometry(QtCore.QRect(210, 50, 131, 23))
        self.button_quit_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_quit_2.setObjectName("button_quit_2")
        self.button_begin_2 = QtWidgets.QPushButton(self.page_5min_nums)
        self.button_begin_2.setGeometry(QtCore.QRect(30, 50, 80, 23))
        self.button_begin_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_begin_2.setObjectName("button_begin_2")
        self.button_exit_3 = QtWidgets.QPushButton(self.page_5min_nums)
        self.button_exit_3.setGeometry(QtCore.QRect(350, 50, 80, 23))
        self.button_exit_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_exit_3.setObjectName("button_exit_3")
        self.button_prev = QtWidgets.QPushButton(self.page_5min_nums)
        self.button_prev.setGeometry(QtCore.QRect(230, 380, 80, 23))
        self.button_prev.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_prev.setObjectName("button_prev")
        self.button_next = QtWidgets.QPushButton(self.page_5min_nums)
        self.button_next.setGeometry(QtCore.QRect(380, 380, 80, 23))
        self.button_next.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_next.setObjectName("button_next")
        self.button_pause_2 = QtWidgets.QPushButton(self.page_5min_nums)
        self.button_pause_2.setGeometry(QtCore.QRect(120, 50, 80, 23))
        self.button_pause_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_pause_2.setObjectName("button_pause_2")
        self.lcdNumber_5min = QtWidgets.QLCDNumber(self.page_5min_nums)
        self.lcdNumber_5min.setGeometry(QtCore.QRect(563, 32, 131, 41))
        self.lcdNumber_5min.setObjectName("lcdNumber_5min")
        self.disp_5min_panel = QtWidgets.QTextBrowser(self.page_5min_nums)
        self.disp_5min_panel.setGeometry(QtCore.QRect(90, 100, 511, 251))
        self.disp_5min_panel.setObjectName("disp_5min_panel")
        self.page_no_label = QtWidgets.QLabel(self.page_5min_nums)
        self.page_no_label.setGeometry(QtCore.QRect(330, 380, 31, 21))
        self.page_no_label.setObjectName("page_no_label")
        self.hide_clock_checkbox = QtWidgets.QCheckBox(self.page_5min_nums)
        self.hide_clock_checkbox.setGeometry(QtCore.QRect(620, 90, 85, 21))
        self.hide_clock_checkbox.setStyleSheet("color: rgb(255, 255, 255);")
        self.hide_clock_checkbox.setObjectName("hide_clock_checkbox")
        self.show_next_digit = QtWidgets.QPushButton(self.page_5min_nums)
        self.show_next_digit.setGeometry(QtCore.QRect(660, 160, 31, 31))
        self.show_next_digit.setStyleSheet("color: rgb(255, 255, 255);")
        self.show_next_digit.setObjectName("show_next_digit")
        self.show_prev_digit = QtWidgets.QPushButton(self.page_5min_nums)
        self.show_prev_digit.setGeometry(QtCore.QRect(620, 160, 31, 31))
        self.show_prev_digit.setStyleSheet("color: rgb(255, 255, 255);")
        self.show_prev_digit.setObjectName("show_prev_digit")
        self.stacked_windows.addWidget(self.page_5min_nums)
        self.page_15min_words = QtWidgets.QWidget()
        self.page_15min_words.setObjectName("page_15min_words")
        self.button_begin_7 = QtWidgets.QPushButton(self.page_15min_words)
        self.button_begin_7.setGeometry(QtCore.QRect(30, 50, 80, 23))
        self.button_begin_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_begin_7.setObjectName("button_begin_7")
        self.button_recall_4 = QtWidgets.QPushButton(self.page_15min_words)
        self.button_recall_4.setGeometry(QtCore.QRect(130, 50, 80, 23))
        self.button_recall_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_recall_4.setObjectName("button_recall_4")
        self.button_quit_7 = QtWidgets.QPushButton(self.page_15min_words)
        self.button_quit_7.setGeometry(QtCore.QRect(230, 50, 131, 23))
        self.button_quit_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_quit_7.setObjectName("button_quit_7")
        self.button_exit_10 = QtWidgets.QPushButton(self.page_15min_words)
        self.button_exit_10.setGeometry(QtCore.QRect(380, 50, 80, 23))
        self.button_exit_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_exit_10.setObjectName("button_exit_10")
        self.lcdNumber_15min_words = QtWidgets.QLCDNumber(self.page_15min_words)
        self.lcdNumber_15min_words.setGeometry(QtCore.QRect(640, 50, 64, 23))
        self.lcdNumber_15min_words.setObjectName("lcdNumber_15min_words")
        self.tableView = QtWidgets.QTableView(self.page_15min_words)
        self.tableView.setGeometry(QtCore.QRect(20, 90, 701, 331))
        self.tableView.setStyleSheet("color: rgb(255, 255, 255);\n"
"gridline-color: rgb(255, 255, 255);")
        self.tableView.setAlternatingRowColors(False)
        self.tableView.setObjectName("tableView")
        self.hide_clock_checkbox_2 = QtWidgets.QCheckBox(self.page_15min_words)
        self.hide_clock_checkbox_2.setGeometry(QtCore.QRect(520, 50, 85, 21))
        self.hide_clock_checkbox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.hide_clock_checkbox_2.setObjectName("hide_clock_checkbox_2")
        self.stacked_windows.addWidget(self.page_15min_words)
        self.page_sn = QtWidgets.QWidget()
        self.page_sn.setObjectName("page_sn")
        self.begin_sn = QtWidgets.QPushButton(self.page_sn)
        self.begin_sn.setGeometry(QtCore.QRect(30, 40, 80, 23))
        self.begin_sn.setStyleSheet("color: rgb(255, 255, 255);")
        self.begin_sn.setObjectName("begin_sn")
        self.recall_sn = QtWidgets.QPushButton(self.page_sn)
        self.recall_sn.setGeometry(QtCore.QRect(130, 40, 80, 23))
        self.recall_sn.setStyleSheet("color: rgb(255, 255, 255);")
        self.recall_sn.setObjectName("recall_sn")
        self.quit_sn = QtWidgets.QPushButton(self.page_sn)
        self.quit_sn.setGeometry(QtCore.QRect(440, 400, 151, 23))
        self.quit_sn.setStyleSheet("color: rgb(255, 255, 255);")
        self.quit_sn.setObjectName("quit_sn")
        self.exit_sn = QtWidgets.QPushButton(self.page_sn)
        self.exit_sn.setGeometry(QtCore.QRect(620, 400, 80, 23))
        self.exit_sn.setStyleSheet("color: rgb(255, 255, 255);")
        self.exit_sn.setObjectName("exit_sn")
        self.timer_sn = QtWidgets.QLCDNumber(self.page_sn)
        self.timer_sn.setGeometry(QtCore.QRect(550, 30, 151, 31))
        self.timer_sn.setObjectName("timer_sn")
        self.hide_timer_sn = QtWidgets.QCheckBox(self.page_sn)
        self.hide_timer_sn.setGeometry(QtCore.QRect(610, 80, 85, 21))
        self.hide_timer_sn.setStyleSheet("color: rgb(255, 255, 255);")
        self.hide_timer_sn.setObjectName("hide_timer_sn")
        self.num_disp_sn = QtWidgets.QTextBrowser(self.page_sn)
        self.num_disp_sn.setGeometry(QtCore.QRect(30, 80, 181, 331))
        self.num_disp_sn.setObjectName("num_disp_sn")
        self.speaker_icon_label = QtWidgets.QLabel(self.page_sn)
        self.speaker_icon_label.setGeometry(QtCore.QRect(350, 120, 161, 141))
        self.speaker_icon_label.setText("")
        self.speaker_icon_label.setObjectName("speaker_icon_label")
        self.stacked_windows.addWidget(self.page_sn)
        self.page_bn = QtWidgets.QWidget()
        self.page_bn.setObjectName("page_bn")
        self.button_prev_bn = QtWidgets.QPushButton(self.page_bn)
        self.button_prev_bn.setGeometry(QtCore.QRect(237, 388, 80, 23))
        self.button_prev_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_prev_bn.setObjectName("button_prev_bn")
        self.button_quit_bn = QtWidgets.QPushButton(self.page_bn)
        self.button_quit_bn.setGeometry(QtCore.QRect(217, 58, 131, 23))
        self.button_quit_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_quit_bn.setObjectName("button_quit_bn")
        self.checkbox_bn = QtWidgets.QCheckBox(self.page_bn)
        self.checkbox_bn.setGeometry(QtCore.QRect(627, 98, 85, 21))
        self.checkbox_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkbox_bn.setObjectName("checkbox_bn")
        self.button_begin_bn = QtWidgets.QPushButton(self.page_bn)
        self.button_begin_bn.setGeometry(QtCore.QRect(37, 58, 80, 23))
        self.button_begin_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_begin_bn.setObjectName("button_begin_bn")
        self.page_no_bn = QtWidgets.QLabel(self.page_bn)
        self.page_no_bn.setGeometry(QtCore.QRect(337, 388, 31, 21))
        self.page_no_bn.setObjectName("page_no_bn")
        self.disp_panel_bn = QtWidgets.QTextBrowser(self.page_bn)
        self.disp_panel_bn.setGeometry(QtCore.QRect(97, 108, 511, 251))
        self.disp_panel_bn.setObjectName("disp_panel_bn")
        self.button_exit_bn = QtWidgets.QPushButton(self.page_bn)
        self.button_exit_bn.setGeometry(QtCore.QRect(357, 58, 80, 23))
        self.button_exit_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_exit_bn.setObjectName("button_exit_bn")
        self.button_recall_bn = QtWidgets.QPushButton(self.page_bn)
        self.button_recall_bn.setGeometry(QtCore.QRect(127, 58, 80, 23))
        self.button_recall_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_recall_bn.setObjectName("button_recall_bn")
        self.button_next_bn = QtWidgets.QPushButton(self.page_bn)
        self.button_next_bn.setGeometry(QtCore.QRect(387, 388, 80, 23))
        self.button_next_bn.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_next_bn.setObjectName("button_next_bn")
        self.timer_bn = QtWidgets.QLCDNumber(self.page_bn)
        self.timer_bn.setGeometry(QtCore.QRect(570, 40, 131, 41))
        self.timer_bn.setObjectName("timer_bn")
        self.stacked_windows.addWidget(self.page_bn)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 20))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.app_descr.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ffffff;\">This app is aimed at users who wish to hone their memorizing skills for events like XMT and WMC. Choose from the following list to begin your training session:</span></p></body></html>"))
        self.button_15min_words.setText(_translate("main_window", "15-minute random list of words"))
        self.button_exit.setText(_translate("main_window", "Exit"))
        self.speed_cards_button.setText(_translate("main_window", "Speed Cards"))
        self.app_title.setText(_translate("main_window", "MnemoPy Arena"))
        self.button_5min_num.setText(_translate("main_window", "5-minute numbers"))
        self.button_sn.setText(_translate("main_window", "Spoken numbers"))
        self.button_bn.setText(_translate("main_window", "Binary numbers"))
        self.time_delay_label.setText(_translate("main_window", "Enter time delay :"))
        self.button_begin.setText(_translate("main_window", "begin"))
        self.button_pause.setText(_translate("main_window", "pause"))
        self.button_hide_timer.setText(_translate("main_window", "hide timer"))
        self.button_recall.setText(_translate("main_window", "recall"))
        self.button_quit.setText(_translate("main_window", "quit to main menu"))
        self.button_exit_2.setToolTip(_translate("main_window", "<html><head/><body><p>exit the program</p></body></html>"))
        self.button_exit_2.setWhatsThis(_translate("main_window", "<html><head/><body><p>exit the program</p></body></html>"))
        self.button_exit_2.setText(_translate("main_window", "exit"))
        self.seconds_label.setText(_translate("main_window", "seconds"))
        self.checkBox.setText(_translate("main_window", "manual"))
        self.button_next_sc.setText(_translate("main_window", "next"))
        self.button_prev_sc.setText(_translate("main_window", "prev"))
        self.card_no_sc.setText(_translate("main_window", "--/52"))
        self.button_quit_2.setText(_translate("main_window", "quit to main menu"))
        self.button_begin_2.setText(_translate("main_window", "begin"))
        self.button_exit_3.setText(_translate("main_window", "exit"))
        self.button_prev.setText(_translate("main_window", "prev"))
        self.button_next.setText(_translate("main_window", "next"))
        self.button_pause_2.setText(_translate("main_window", "pause"))
        self.page_no_label.setText(_translate("main_window", "0/10"))
        self.hide_clock_checkbox.setText(_translate("main_window", "hide clock"))
        self.show_next_digit.setText(_translate("main_window", ">"))
        self.show_prev_digit.setText(_translate("main_window", "<"))
        self.button_begin_7.setText(_translate("main_window", "begin"))
        self.button_recall_4.setText(_translate("main_window", "recall"))
        self.button_quit_7.setText(_translate("main_window", "quit to main menu"))
        self.button_exit_10.setText(_translate("main_window", "exit"))
        self.hide_clock_checkbox_2.setText(_translate("main_window", "hide clock"))
        self.begin_sn.setText(_translate("main_window", "begin"))
        self.recall_sn.setText(_translate("main_window", "recall"))
        self.quit_sn.setText(_translate("main_window", "quit to main menu"))
        self.exit_sn.setText(_translate("main_window", "exit"))
        self.hide_timer_sn.setText(_translate("main_window", "hide timer"))
        self.button_prev_bn.setText(_translate("main_window", "prev"))
        self.button_quit_bn.setText(_translate("main_window", "quit to main menu"))
        self.checkbox_bn.setText(_translate("main_window", "hide clock"))
        self.button_begin_bn.setText(_translate("main_window", "begin"))
        self.page_no_bn.setText(_translate("main_window", "0/10"))
        self.button_exit_bn.setText(_translate("main_window", "exit"))
        self.button_recall_bn.setText(_translate("main_window", "recall"))
        self.button_next_bn.setText(_translate("main_window", "next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
